// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
void ui_event_kedarnath(lv_event_t * e);
extern lv_obj_t * ui_kedarnath;
void ui_event_rishikesh(lv_event_t * e);
extern lv_obj_t * ui_rishikesh;
void ui_event_home(lv_event_t * e);
extern lv_obj_t * ui_home;
void ui_event_fourPeople(lv_event_t * e);
extern lv_obj_t * ui_fourPeople;
void ui_event_family(lv_event_t * e);
extern lv_obj_t * ui_family;
void ui_event_otherFriends(lv_event_t * e);
extern lv_obj_t * ui_otherFriends;
extern lv_obj_t * ui_home1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_otherFriends;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1_png);    // assets/1.png
LV_IMG_DECLARE(ui_img_2_png);    // assets/2.png
LV_IMG_DECLARE(ui_img_3_png);    // assets/3.png
LV_IMG_DECLARE(ui_img_4_png);    // assets/4.png
LV_IMG_DECLARE(ui_img_5_png);    // assets/5.png
LV_IMG_DECLARE(ui_img_6_png);    // assets/6.png
LV_IMG_DECLARE(ui_img_home2_png);    // assets/home2.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
